# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/genDevo/Stardew-Armory/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="stardewarmory" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="1.16.5-1.1.1" #mandatory
 # A display name for the mod
displayName="Stardew Armory" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/genDevo/Stardew-Armory" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="SAlogo.png" #optional
# A text field displayed in the mod UI
credits="ConcernedApe for the original Stardew Valley, TurtyWurty & KaupenJoe for learning how to code all this, and Hasshbrowns for inspiration in many aspects. Credit to Kuri_Pa for Chinese language support and credit to peachimarii for the adventurer's guild building." #optional
# A text field displayed in the mod UI
authors="genericZen" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Welcome to Stardew Armory! The main goal of this mod is to add many of the weapons and combat items from Stardew Valley into Minecraft. This currently includes all normally obtainable weapons, iridium tools, rings, custom blocks, and more!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.stardewarmory]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.stardewarmory]]
modId="curios"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.16.5-4.0.5.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.stardewarmory]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
